### ISSUE TITLE
Variables not pass through to config template correctly?

### ISSUE THREAD

**Issue by CpuID** [justindowning/puppet-statsd#8]
See below:

Error: Failed to parse template statsd/localConfig.js.erb:
  Filepath: /usr/src/puppet/modules/statsd/templates/localConfig.js.erb
  Line: 4
  Detail: undefined method `each' for nil:NilClass

Seems that backends is nil, due to not being passed through natively from the parameters on class { 'statsd': }

**Comment by ricoli** [comment]
I'm experiencing the same thing when using hiera:
```yaml
statsd::backends:
  - statsd-influxdb-backend
```
The thing is, the template calls the variables as if they were defined in the statsd::config, which they aren't. The line in question:
```
, backends: [<% @backends.each do |backend| -%>
```
when backends is not a variable in statsd::config. Therefore, in the template it should be @statsd::backends no?

**Comment by johanneskunze** [comment]
Same here. @backends not defined.

Trusty - Puppet 3.7.4 - Future Parser

**Comment by timols** [comment]
Yep, since upgrading from 2.0.0 to 2.5.0 I'm being bitten by this too.

**Comment by ricoli** [comment]
@justindowning would inheriting statsd class be acceptable? https://github.com/justindowning/puppet-statsd/pull/27 - all specs pass...

**Comment by justindowning** [comment]
This is fixed in 2.6.0 and published to the [Forge](https://forge.puppetlabs.com/jdowning/statsd). Thanks everyone for your help and patience!
